// This file is auto-generated by Specta
// Run `cargo build` to regenerate types

// Placeholder - types will be generated automatically
export type GreetParams = { name: string }
export type GreetResult = string

export type GetAppInfoResult = {
  name: string
  version: string
  platform: string
}
